export const skipsizedata = [
     {
        index:1,
        title:"4 Yard Skip",
        description:"14 day hire period",
        price:"$211",
        yards:"4 Yards",
    },
      {
        index:2,
        title:"5 Yard Skip",
        description:"14 day hire period",
        price:"$241",
        yards:"5 Yards",
    },
      {
        index:3,
        title:"6 Yard Skip",
        description:"14 day hire period",
        price:"$264",
        yards:"6 Yards",
    },
    {
        index:4,
        title:"8 Yard Skip",
        description:"14 day hire period",
        price:"$295",
        yards:"8 Yards",
    },
      {
        index:5,
        title:"10 Yard Skip",
        description:"14 day hire period",
        price:"$356",
        yards:"10 Yards",
    },
      {
        index:6,
        title:"12 Yard Skip",
        description:"14 day hire period",
        price:"$390",
        yards:"12 Yards",
    },
    {
        index:7,
        title:"14 Yard Skip",
        description:"14 day hire period",
        price:"$434",
        yards:"14 Yards",
    },
      {
        index:8,
        title:"16 Yard Skip",
        description:"14 day hire period",
        price:"$510",
        yards:"16 Yards",
    },
       {
        index:9,
        title:"20 Yard Skip",
        description:"14 day hire period",
        price:"$802",
        yards:"20 Yards",
    },
      {
        index:10,
        title:"40 Yard Skip",
        description:"14 day hire period",
        price:"$877",
        yards:"40 Yards",
    }
]